### ISSUE TITLE
webpack.prod.conf.js 引入 clean-webpack-plugin 的错误

### ISSUE THREAD

**Issue by bluce** [fireworksflyaway/basic-demo#2]
webpack.prod.conf.js
const CleanWebpackPlugin = require('clean-webpack-plugin');

应该改成 
const { CleanWebpackPlugin } = require('clean-webpack-plugin');

**Comment by fireworksflyaway** [comment]
clean-webpack-plugin插件3.0版确实应该是const { CleanWebpackPlugin } = require('clean-webpack-plugin');

**Comment by fireworksflyaway** [comment]
2.0版应该const CleanWebpackPlugin = require('clean-webpack-plugin');

**Comment by bluce** [comment]
好的，了解，谢谢
